name: Render Paper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc
      run: sudo apt install pandoc pandoc-citeproc texlive-full texlive-publishers
    - name: Render PDF
      run: make
