name: Render Paper

on:
  push:
    branches: [ master ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX and pandoc
        run: |
          sudo apt update
          sudo apt install -y \
            pandoc \
            pandoc-citeproc \
            texlive-bibtex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-science \
            texlive-publishers  # This contains IEEEtran.cls

      - name: Make pdf
        run: |
          mkdir -p build
          pandoc -o build/paper.pdf \
            --bibliography=bibliography.bib \
            --csl=bibliography.csl \
            -s -f markdown \
            --template=template.latex \
            paper.md metadata.yaml

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
