name: Render Paper to PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt install pandoc pandoc-citeproc texlive-scheme-full texlive-full texlive-publishers

      - name: Render PDF
        run: |
          sudo pandoc -o build/paper.pdf \
          --bibliography=bibliography.bib \
          --csl=bibliography.csl \
          -s -f markdown \
          --template=template.latex \
          paper.md metadata.yaml


      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: build/paper.pdf