name: Render Paper to PDF

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-full texlive-publishers

      - name: Render PDF
        run: |
          mkdir -p build
          pandoc -o build/paper.pdf \
          --bibliography=bibliography.bib \
          --csl=bibliography.csl \
          -s -f markdown \
          --template=template.latex \
          paper.md metadata.yaml